version: '3'

services:
  run:
    container_name: local-althingi-server-run
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    environment:
      STORE_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8083
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src/
      - ./lib/:/app/lib/
    command: bash -c "denon run --allow-net --allow-env --allow-read --unstable src/index.ts"

  test:
    container_name: local-althingi-server-test
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/app/src/
      - ./lib/:/app/lib/
      - ./test/:/app/test/
    command: bash -c "deno test"